---

- name: Create storage location
  file: path={{ storage_location }} owner=bareos group=bareos  mode=0770 state=directory

- name: Push Bareos-Storage configuration files to Director
  template: src={{item.src}} dest={{item.dest}}  mode=0640 owner=bareos group=bareos
  with_items:
      - { src: 'storage/File.conf', dest: '/etc/bareos/bareos-dir.d/storage/File.conf' }
  notify: reload bareos-director

- name: Enable bareos director service
  action: service name=bareos-dir state=started enabled=yes

