---

- name: Install Tower/AWX cli tool
  yum:
    name: ansible-tower-cli
    state: present

- name: Configure tower-cli
  shell: tower-cli config {{ item }}
  with_items:
    - "host http://{{ tower_cli_host }}"
    - "username {{ tower_cli_user }}"
    - "password {{ tower_cli_pass }}"
    - "verify_ssl false"


- name: Test connection for AWX server
  shell: tower-cli host list
