- name: Bareos database
  hosts: director
  roles:
    - role: bareos-database

- name: Bareos director
  hosts: director
  roles:
    - role: bareos-director
    - role: bareos-webui

- name: Tower/AWX CLI 
  hosts: director
  roles:
    - role: tower-cli
